kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: limoli/capstone:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always

---

# Expose container using LoadBalancer, reachable at port 8000 and forwards to a container that listens in port 80
kind: Service
apiVersion: v1
metadata:
  name: react-app-lb
  labels:
    app: react-app-lb
spec:
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: react-app
  type: LoadBalancer

# NodePort exposes the service on each node’s IP address at a static port.
#kind: Service
#apiVersion: v1
#metadata:
#  name: react-app
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP
#      nodePort: 31000
#  selector:
#    app: react-app